### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by muelli** [kallaspriit/elm-basic-auth#1]
Hi, do you have any plans for bumping the library to Elm 0.19?
Would you accept any changes that would make the code Elm 0.19 compatible?
It seems simple enough.

**Comment by kallaspriit** [comment]
PR is welcome :)

**Comment by Natim** [comment]
Ok I am working on it.

**Comment by Natim** [comment]
Refs https://github.com/kallaspriit/elm-basic-auth/pull/2

**Comment by muelli** [comment]
hm. the library is not showing up on https://package.elm-lang.org/ though, is it?
